Moved drivers into package script
and install packages based on hostname instead of several menu options

diff --git a/bin/dtools b/bin/dtools
--- a/bin/dtools
+++ b/bin/dtools
@@ -2,9 +2,7 @@
 
 ### Main launch script which sets some variables
 device_menu(){
-    echo "(1) Install Lact                  (2) Install Nvidia Driver"
-    echo "(3) Install packages              "
-    echo "(4) Configure Desktop             (5) Configure Laptop"
+    echo "(1) Install packages              (2) Configure system"
     echo "(0) Exit"
     printf "Option: "
     read -r input
@@ -12,24 +10,11 @@ device_menu(){
     case $input in
 
         1)
-            "$HOME"/.local/share/dsks-tools/bin/drivers "lact"
-            ;;
-
-        2)
-            "$HOME"/.local/share/dsks-tools/bin/drivers "nvidia"
-            ;;
-
-        3)
             "$HOME"/.local/share/dsks-tools/bin/packages
             ;;
 
-        4)
-            "$HOME"/.local/share/dsks-tools/bin/system "DESKTOP"
-            ;;
-
-        5)
-            
-            "$HOME"/.local/share/dsks-tools/bin/system "LAPTOP"
+        2)
+            "$HOME"/.local/share/dsks-tools/bin/system
             ;;
 
         0)
@@ -109,14 +94,26 @@ gcache(){
 
 }
 
+build_cockpit_files(){
+    if [ -d "/usr/share/cockpit" ]; then
+        cd "$HOME"/.local/share/dsks-tools/temp || exit
+        git clone https://github.com/cockpit-project/cockpit-files.git
+        cd "cockpit-files" || exit
+        make
+        sudo make install
+        rm -r -f "$HOME"/.local/share/dsks-tools/temp/cockpit-files
+    else
+        echo "Cockpit not found. Not installing cockpit-files."
+    fi
+}
+
 update(){
     if [ "$DISTRO" == "opensuse-tumbleweed" ]
     then
         sudo zypper -n dup --auto-agree-with-licenses
-        sudo flatpak update -y
-        sudo flatpak remove --unused -y
-        "$HOME"/.local/share/dsks-tools/bin/system "cockpit-files"
-
+        flatpak update -y
+        flatpak remove --unused -y
+        build_cockpit_files
     else
         echo ""
     fi
@@ -129,9 +126,6 @@ dsks_tools(){
     elif [ "$1" == "--containers" ] || [ "$1" == "-c" ] || [ "$1" == "containers" ]
     then
         containers_menu
-    elif [ "$1" == "--menu" ] || [ "$1" == "-m" ] || [ "$1" == "menu" ]
-    then
-        main_menu
     elif [ "$1" == "--gcache" ] || [ "$1" == "-g" ] || [ "$1" == "gcache" ]
     then
         gcache
@@ -168,7 +162,6 @@ dsks_tools_help(){
     echo "Available arguments:"
     echo "  --devices, -d, devices          # opens menu for setting up my devices"
     echo "  --containers, -c, containers    # opens menu for creating containers"
-    echo "  --menu, -m, menu                # opens main menu"
     echo "  --gcache, -g, gcache            # cleans shader caches for select electron apps"
     echo "  --update, -u update             # update system"
     echo "  --pull, -p, pull                # updates these tools"
@@ -183,5 +176,5 @@ export COPYRIGHT="Copyright (c) 2024-2026 Jordan Bottoms"
 export PROTON_MAIL="https://proton.me/download/mail/linux/1.12.1/ProtonMail-desktop-beta.rpm"
 export PROTON_PASS="https://proton.me/download/pass/linux/proton-pass-1.34.2-1.x86_64.rpm"
 export PROTON_AUTH="https://proton.me/download/authenticator/linux/ProtonAuthenticator-1.1.4-1.x86_64.rpm"
-DISTRO=$(source /etc/os-release ; echo $ID)                                                
+DISTRO=$(source /etc/os-release ; echo $ID)
 dsks_tools "$1"
