only use $TOOLS_FOLDER for installing
and use $HOME/.local/share/dsks-tools for path

diff --git a/dtools b/dtools
--- a/dtools
+++ b/dtools
@@ -232,11 +232,8 @@ dsks_tools(){
         update
     elif [ "$1" == "--pull" ] || [ "$1" == "-p" ] || [ "$1" == "pull" ]
     then
-        cd "$TOOLS_FOLDER" || exit
+        cd "$HOME"/.local/share/dsks-tools || exit
         git stash && git pull
-    elif [ "$1" == "--install" ] || [ "$1" == "-i" ] || [ "$1" == "install" ]
-    then
-        install
     elif [ -z "$1" ]
     then
         echo "dtools: no option given"
@@ -258,7 +255,6 @@ dsks_tools_help(){
     echo "  dtools --containers"
     echo "  dtools --pull"
     echo "  dtools --update"
-    echo "  dtools --install"
     echo ""
     echo ""
     echo "Available arguments:"
@@ -269,20 +265,26 @@ dsks_tools_help(){
     echo "  --gcache, -g, gcache            # cleans shader caches for select electron apps"
     echo "  --update, -u update             # update system"
     echo "  --pull, -p, pull                # updates these tools"
-    echo "  --install, -i, install          # copies dsks-tools to $HOME/.local/share"
 }
 
 install(){
-    cp -r "$TOOLS_FOLDER" "$HOME"/.local/share/dsks-tools
-    ln -s "$HOME"/.local/share/dsks-tools/dtools "$HOME"/.local/bin/dtools
+    if [ -d "$HOME/.local/share/dsks-tools" ]; then
+        dsks_tools "$1"
+    else
+        echo "dsks-tools not found under $HOME/.local/share."
+        echo "This will be copied over and run from there"
+        TOOLS_FOLDER=$(pwd)  # stores full path for dsks-tools
+        cp -r "$TOOLS_FOLDER" "$HOME"/.local/share/dsks-tools
+        ln -s "$HOME"/.local/share/dsks-tools/dtools "$HOME"/.local/bin/dtools
+        mkdir "$HOME"/.local/share/dsks-tools/temp
+    fi
+    
 }
-export TOOLS_FOLDER
+
 export DISTRO
 export COPYRIGHT="Copyright (c) 2024-2026 Jordan Bottoms"
 export PROTON_MAIL="https://proton.me/download/mail/linux/1.10.1/ProtonMail-desktop-beta.rpm"
 export PROTON_PASS="https://proton.me/download/pass/linux/proton-pass-1.32.11-1.x86_64.rpm"
 export PROTON_AUTH="https://proton.me/download/authenticator/linux/ProtonAuthenticator-1.1.4-1.x86_64.rpm"
-TOOLS_FOLDER=$(pwd)  # stores full path for dsks-tools
 DISTRO=$(source /etc/os-release ; echo $ID)                                                
-mkdir "$TOOLS_FOLDER"/temp
-dsks_tools "$1"
+install "$1"
